In [3]:
import numpy

def cal_pop_fitness(equation_inputs, pop):
    fitness = numpy.sum(pop*equation_inputs, axis=1)
    return fitness

def select_mating_pool(pop, fitness, num_parents):
    parents = numpy.empty((num_parents, pop.shape[1]))
    for parent_num in range(num_parents):
        max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        parents[parent_num, :] = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
    return parents

def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size)
    crossover_point = numpy.uint8(offspring_size[1]/2)

    for k in range(offspring_size[0]):
        parent1_idx = k%parents.shape[0]
        parent2_idx = (k+1)%parents.shape[0]
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return offspring

def mutation(offspring_crossover):
    for idx in range(offspring_crossover.shape[0]):
        random_value = numpy.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
    return offspring_crossover

In [4]:
# y = w1x1 + w2x2 + w3x3 + w4x4 + w5x5 + 6wx6, где (x1, x2, x3, x4, x5, x6) = (4, -2,3.5,5, -11, -4.7)

equation_inputs = [4,-2,3.5,5,-11,-4.7]

num_weights = 6
sol_per_pop = 8
num_parents_mating = 4

pop_size = (sol_per_pop,num_weights)
new_population = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)
print(new_population)

num_generations = 5
for generation in range(num_generations):
    print("Generation : ", generation)
    fitness = cal_pop_fitness(equation_inputs, new_population)
    parents = select_mating_pool(new_population, fitness, num_parents_mating)
    offspring_crossover = crossover(parents, offspring_size=(pop_size[0]-parents.shape[0], num_weights))
    offspring_mutation = mutation(offspring_crossover)
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring_mutation

    print("Best result : ", numpy.max(numpy.sum(new_population*equation_inputs, axis=1)))

fitness = cal_pop_fitness(equation_inputs, new_population)
best_match_idx = numpy.where(fitness == numpy.max(fitness))

print("Best solution : ", new_population[best_match_idx, :])
print("Best solution fitness : ", fitness[best_match_idx])

[[ 1.11743674 -1.44946467 -3.01728362  2.38485069  3.79717389 -1.66403585]
 [-2.93193791 -3.99472242  2.66740301  2.43296799  1.48373981  2.218141  ]
 [ 0.67681229  1.95865019  0.79481053 -2.70339762 -1.93012081  3.81473038]
 [ 1.11162692  3.84469294  0.19726249 -0.75498775 -3.26750384 -2.77172196]
 [ 0.61908264 -1.94605381  3.41351051  3.50981898 -3.48924844 -2.09752847]
 [-0.17613391 -0.23355372  2.78926167  0.79699792  1.48183094  2.18928296]
 [ 2.32010926  2.12213564 -0.32593792  3.55891519  2.10557476 -1.02717613]
 [-3.59182869 -3.40339279  2.56696049  2.13954869  1.75958181  2.49267353]]
Generation :  0
Best result :  84.10493651922239
Generation :  1
Best result :  88.437684955671
Generation :  2
Best result :  95.81996253464975
Generation :  3
Best result :  98.6363557461203
Generation :  4
Best result :  98.6363557461203
Best solution :  [[[ 0.61908264 -1.94605381  3.41351051  3.50981898 -4.81028655
   -2.09752847]]]
Best solution fitness :  [98.63635575]
